// Generated by ts-to-zod
import { z } from "zod";

export const recipeSchema = z.object({
  url: z.string(),
  name: z.string(),
  image: z.string(),
  description: z.string(),
  cookTime: z.string(),
  prepTime: z.string(),
  totalTime: z.string(),
  recipeYield: z.string(),
  recipeIngredients: z.array(z.string()),
  recipeInstructions: z.array(z.string()),
  recipeCategories: z.array(z.string()),
  recipeCuisines: z.array(z.string()),
  recipeTypes: z.array(z.string()),
  keywords: z.array(z.string()),
});
